# Automatically terminate Gradle daemon after 60 seconds of inactivity
org.gradle.daemon.idletimeout=60000

# Cap maximum RAM usage to 2GB instead of 8GB
org.gradle.jvmargs=-Xmx2G -XX:MaxMetaspaceSize=1G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
