// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDblYXiPBuJ91NPv5VbHcuLqY5YEG-2Ssg',
    appId: '1:106375247397:web:efb213dd31084eb564f1cc',
    messagingSenderId: '106375247397',
    projectId: 'yank-b3078',
    authDomain: 'yank-b3078.firebaseapp.com',
    storageBucket: 'yank-b3078.firebasestorage.app',
    measurementId: 'G-5G6C1K2RQF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIqd02kTVhcVyNaUMW3V7dUQxxCA5c9dI',
    appId: '1:106375247397:android:2093b6591200d59264f1cc',
    messagingSenderId: '106375247397',
    projectId: 'yank-b3078',
    storageBucket: 'yank-b3078.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbW3w158Dod6_ORXLvxwhrlENsHis1Nvc',
    appId: '1:106375247397:ios:75943986d861a99c64f1cc',
    messagingSenderId: '106375247397',
    projectId: 'yank-b3078',
    storageBucket: 'yank-b3078.firebasestorage.app',
    iosBundleId: 'com.example.yank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbW3w158Dod6_ORXLvxwhrlENsHis1Nvc',
    appId: '1:106375247397:ios:75943986d861a99c64f1cc',
    messagingSenderId: '106375247397',
    projectId: 'yank-b3078',
    storageBucket: 'yank-b3078.firebasestorage.app',
    iosBundleId: 'com.example.yank',
  );
}
